services:
  order.api:
    build:
      context: .
      dockerfile: src/Order.API/Dockerfile
    container_name: order-host
    ports:
      - "5000:8080"
    volumes:
      - logs:/app/logs:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERILOG__MINIMUMLEVEL=Information
    networks:
      - orders-network

networks:
  orders-network:
    driver: bridge

volumes:
  logs: